# Generated by Django 4.2.2 on 2023-06-29 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gpx',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_location', models.CharField(max_length=500)),
                ('end_location', models.CharField(max_length=500)),
                ('transport_method', models.CharField(choices=[('W', 'walking'), ('C', 'cycling')], max_length=1)),
                ('gpxfile', models.FileField(blank=True, null=True, upload_to='')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
